services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: LetMeIn
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  be:
    build: ./be
    container_name: signup-be
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: LetMeIn
      SPRING_UPLOADS: /storage
      SPRING_PROFILES_ACTIVE: "docker"
      JWT_SECRET: "15619653dfsdfsf89165fsd56f89fakthodnebezpecne,tocumite,ze?chachachacahfaktdobryklics51f6sd5f1sd6f1sd68f1af861sdf891asd89fsd89f4f89ertyuikmnbvcxcfghj"
      JWT_VALID_MINUTES: "180"
      INIT_EMAIL: fake@fake.com
      INIT_NAME: admin
      INIT_PASSWORD: changeit
      INIT_ENABLED: false
    volumes:
      - ./uploads:/storage
  fe:
    build: ./fe
    container_name: signup-fe
    ports:
      - "80:80"
    depends_on:
      - be

volumes:
  pgdata: {}
